### ISSUE TITLE
Talking Animation + expressions - Main Character

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam48#151]

**Comment by fan1268** [comment]
![MainChaSuitmouthopen.png](https://zube.io/files/enigmadragons/0af77955edbef7fae31a934cef29d922-mainchasuitmouthopen.png)
mouth open

**Comment by fan1268** [comment]
![MainChaSuitmouthopen.png](https://zube.io/files/enigmadragons/c28fbb6a9ed9f3d92f5a96bbdeccb518-mainchasuitmouthopen.png)

**Comment by fan1268** [comment]
![MainChaSuitjoy.png](https://zube.io/files/enigmadragons/ff833b61c88a2e8d274dc2c13dbc53d7-mainchasuitjoy.png)![MainChaSuitjoymouthopen.png](https://zube.io/files/enigmadragons/9238fc5aefbba1d8d569e0e9d124a622-mainchasuitjoymouthopen.png)![MainChaSuitmadmouthopen.png](https://zube.io/files/enigmadragons/f6a694793e7dedc02eba5a4379e3ffa3-mainchasuitmadmouthopen.png)![MainChaSuitmad.png](https://zube.io/files/enigmadragons/34b3e7709f0ebc506743a38c76c4d15c-mainchasuitmad.png)![MainChaSuitsad.png](https://zube.io/files/enigmadragons/d8e3d3f9b421e3d1b52ea7828f105ad3-mainchasuitsad.png)![MainChaSuitsadmouthopen.png](https://zube.io/files/enigmadragons/bfb33342f5e3eef336970502bcef4282-mainchasuitsadmouthopen.png)

**Comment by fan1268** [comment]
![MainChaSuitjoy.png](https://zube.io/files/enigmadragons/ff833b61c88a2e8d274dc2c13dbc53d7-mainchasuitjoy.png)![MainChaSuitjoymouthopen.png](https://zube.io/files/enigmadragons/9238fc5aefbba1d8d569e0e9d124a622-mainchasuitjoymouthopen.png)![MainChaSuitmad.png](https://zube.io/files/enigmadragons/34b3e7709f0ebc506743a38c76c4d15c-mainchasuitmad.png)![MainChaSuitmadmouthopen.png](https://zube.io/files/enigmadragons/47eda4c395b53ae25eb72514de0293a7-mainchasuitmadmouthopen.png)![MainChaSuitmouthopen.png](https://zube.io/files/enigmadragons/c28fbb6a9ed9f3d92f5a96bbdeccb518-mainchasuitmouthopen.png)![MainChaSuitsad.png](https://zube.io/files/enigmadragons/d8e3d3f9b421e3d1b52ea7828f105ad3-mainchasuitsad.png)![MainChaSuitsadmouthopen.png](https://zube.io/files/enigmadragons/bfb33342f5e3eef336970502bcef4282-mainchasuitsadmouthopen.png)
