### ISSUE TITLE
Add shocked expresion sprites

### ISSUE THREAD

**Issue by ChaosTheLegend** [EnigmaDragons/LDJam48#193]
![image.png](https://zube.io/files/enigmadragons/371a5bc578c215ea65a0027e8d8456ba-image.png)

**Comment by fan1268** [comment]
![nerdvillainshock.png](https://zube.io/files/enigmadragons/a00139514fd3091140271588428c93b0-nerdvillainshock.png)![MainChaSuitshock.png](https://zube.io/files/enigmadragons/f428641febcefe613afe580b4941c6f2-mainchasuitshock.png)![oldmanvillainshock.png](https://zube.io/files/enigmadragons/dd63bea560ae726c0acdd2ffb7edf3a4-oldmanvillainshock.png)![security guardshock.png](https://zube.io/files/enigmadragons/2ff72793afb947b2e76c54f944bb3a12-security-guardshock.png)

**Comment by fan1268** [comment]
![MainChaSuitshock.png](https://zube.io/files/enigmadragons/509674a9b9875ddb0683c238f4c45248-mainchasuitshock.png)![nerdvillainshock.png](https://zube.io/files/enigmadragons/a00139514fd3091140271588428c93b0-nerdvillainshock.png)![oldmanvillainshock.png](https://zube.io/files/enigmadragons/dd63bea560ae726c0acdd2ffb7edf3a4-oldmanvillainshock.png)![security guardshock.png](https://zube.io/files/enigmadragons/2ff72793afb947b2e76c54f944bb3a12-security-guardshock.png)
