### ISSUE TITLE
Character: Underwater Scientist

### ISSUE THREAD

**Issue by ZavixDragon** [EnigmaDragons/LDJam48#205]

**Comment by fan1268** [comment]
![scientist.png](https://zube.io/files/enigmadragons/3f08bf18bd963bfa3d385ba24b07ee5d-scientist.png)![scientistjoy.png](https://zube.io/files/enigmadragons/d6cfa0ed78f8c9f9f47722a04e51e8b8-scientistjoy.png)![scientistsad.png](https://zube.io/files/enigmadragons/2602a10261bb3d939a34131c7f3c89a5-scientistsad.png)![scientistshock.png](https://zube.io/files/enigmadragons/1fd022bb894a497543e9946bdbbc4265-scientistshock.png)![scientistsus.png](https://zube.io/files/enigmadragons/2cc2419124ed4b3758978603e9bc25e8-scientistsus.png)
