### ISSUE TITLE
Create Screen border with some random exclamation marks at various angles, and a vignette (show be white with alpha, so we can color it based on intensity)

### ISSUE THREAD

**Issue by SilasReinagel** [EnigmaDragons/LDJam48#277]

**Comment by fan1268** [comment]
![348137_action-lines-png.png](https://zube.io/files/enigmadragons/1ffbf5a2a08d6c9521d479234b96c248-348137_action-lines-png.png)

**Comment by fan1268** [comment]
![comic-book-action-lines-speed-manga-frame-cartoon-background-black-white-vector-retro-illustration-transparent-146160804 (1).jpg](https://zube.io/files/enigmadragons/7c210aa9630d259ea3560d6249cd8d2e-comic-book-action-lines-speed-manga-frame-cartoon-background-black-white-vector-retro-illustration-transparent-146160804-1.jpg)

**Comment by fan1268** [comment]
![actionlines.png](https://zube.io/files/enigmadragons/34111051bf480f41aa34efa8965bf72e-actionlines.png)
