### ISSUE TITLE
Different options. Accessing the options from the Main Menu offers more choices than accessing them from in game. (Perhaps this is intentional?) (sceenshots)

### ISSUE THREAD

**Issue by gordykeene** [EnigmaDragons/LDJam48#350]
Main menu example:
![2021-04-26_12h04_15.png](https://zube.io/files/enigmadragons/0b664cdd3d458e9f0953e53a4e38cccb-2021-04-26_12h04_15.png)

In game example:
![2021-04-26_11h51_21.png](https://zube.io/files/enigmadragons/44c03f806163b099ef250c981c62ad06-2021-04-26_11h51_21.png)

**Comment by SilasReinagel** [comment]
This is intentional.
